---
- name: Prepare System For RedHat
  block:
    - name: Install Packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - chrony
        - curl
    - name: Allow Ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      loop: [ '8200/tcp' ]
  when:
    ansible_os_family == "RedHat"

- name: Security Settings For Debian
  block:
    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - chrony
        - curl
        - apt-transport-https
        - iptables-persistent
    - name: Allow TCP Ports
      iptables:
        chain: INPUT
        rule_num: '1'
        action: insert
        protocol: tcp
        jump: ACCEPT
        destination_port: "{{ item }}"
      loop: [ '8200' ]
      notify:
        - iptables save
  when:
    ansible_os_family == "Debian"